version: '3'
services:
  app:
    image: python:3.6
    volumes:
      # Aplicação
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    networks:
      - app-network
    # environment:
      # - DB_NAME=abc_sender
  db:
    build: db
    container_name: python-ragnarok-db
    restart: always
    tty: true
    ports:
      - "3308:3306"
    volumes:
      - ./db/dbdata:/var/lib/mysql
      - ./db/sql-files:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=ragnarok
      - MYSQL_ROOT_PASSWORD=R00t+
      - MYSQL_USER=ragnarok
      - MYSQL_PASSWORD=ragnarok
    networks:
      - app-network

networks:
  app-network:
    driver: bridge